# -*- coding: utf-8 -*-
"""Hackthon-python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dF4kCowfL7oC694SuyL9mu6z8kz_L3v5
"""

import numpy as np

import pandas as pd

"""**Functions & Fibonacci Sequence**"""

def fibonacci(n):
  """
  This function generates the Fibonacci sequence up to a specified term n.

  Args:
      n: An integer representing the number of terms in the Fibonacci sequence.

  Returns:
      A list containing the first n terms of the Fibonacci sequence.
  """
  if n <= 1:
    return n
  else:
    return fibonacci(n-1) + fibonacci(n-2)

# Get user input for the number of terms
n = int(input("Enter the number of terms in the Fibonacci sequence: "))

# Generate the Fibonacci sequence
fibonacci_sequence = [fibonacci(i) for i in range(n)]

# Print the generated Fibonacci sequence
print("Fibonacci sequence:", fibonacci_sequence)

"""**Python Conditional Statements**"""

age = int(input("Enter your age: "))

if age >= 18:
  print("You are eligible to vote")
else:
  print("You are not eligible to vote")